### ISSUE TITLE
Memory allocation problem

### ISSUE THREAD

**Issue by wllm-rbnt** [quarkslab/binbloom#1]
I just tried to test the tool on a Linux VM with a limited amount of RAM (4GB).
Whatever the binary I try to analyze, it always returns the same error:
    binbloom: [...]/binbloom.c:592: main: Assertion `score_base_address' failed.

The reason is that, at line 591, the code unconditionally tries to allocate 4GB of RAM (minus 4 bytes).
591: score_base_address = (uint32_t *)calloc(1024 * 1024 * 1024 - 1, sizeof(uint32_t));
592: assert(score_base_address);

The calloc call fails, then program is aborted on line 592.

**Comment by gheilles** [comment]
I thought 4GB of RAM was reasonable... OK I'll change that but the software might take even longer to execute. I'll add a lowram option or something like that.

**Comment by gheilles** [comment]
Fixed, now the memory consumption is around 5x the size of the firmware. I changed the data structures and the algorithm. Also, the new version is approximately 2x faster. The results are the same (tested on several firmwares).
Thank you for your inputs.
