### ISSUE TITLE
Tag a new version with latest fixes

### ISSUE THREAD

**Issue by erdnaxe** [quarkslab/binbloom#11]
Since `v2.0` tag, MacOS support has been fixed but no minor release has been made yet.

What is your release policy? Would you be okay with the idea of releasing a new minor version to enable MacOS distributions to target a "stable" release (https://github.com/NixOS/nixpkgs/pull/176521#issuecomment-1147487832)?

Best regards,

**Comment by virtualabs** [comment]
Version 2.1 has just been released, including all the latest fixes brought to binbloom.
