### ISSUE TITLE
[Enhancement] Add support to more kinds of firmware

### ISSUE THREAD

**Issue by RandLily** [quarkslab/binbloom#12]
I found that if the correct base address is 0x08004800，binbloom can only find address just like 0x?????000，So I fix that as my PR。
But there is a new issue，when the correct base address is 0x3f80，binbloom failed too，and use the same way to fix can only make binbloom run overtime。
I think we can solve the problem by referring to https://github.com/soyersoyer/basefind2  ,i use this method on my ida script https://github.com/RandLily/iBAS  ,it's nice。

**Comment by virtualabs** [comment]
I am currently implementing a new option to allow the user to specify the base address alignment value (by default it will be 0x1000, as for the current version of the code). Using this option, one may want to search for more precise addresses (but it may take longer to process). It may help handling these specific cases, I hope.
