### ISSUE TITLE
[Enhancement] Limit point of interest being processed

### ISSUE THREAD

**Issue by nikaiw** [quarkslab/binbloom#14]
For big firmware ( > 100 MB ) binbloom takes really (really) long to process. It would be great to have an option to limit the amount of points of interest being taking into account to compute candidate. The same way we can limit the amount of strings being taken into account in rbasefind using the length.

**Comment by virtualabs** [comment]
I am not really sure that the number of points of interest are causing this latency in binbloom. I made some experiments by limiting them on a big file (>100M), and binbloom did not give me valuable results when the number of points of interest is limited. In fact, if you limit the number of POIs to a low value (say, at most 200 POIs) it may miss the interesting ones and therefore the computation performed by binbloom is biased and won't give valuable results.

The time spent on recovering a firmware base address is defined by the number of POIs and the size of the analyzed file, as binbloom tries all the possible combinations between potential pointers (well, basically any data in the file that may be considered as a pointer) and identified POIs. You may reduce processing time by either reducing the number of POIs or the size of the file. In both cases it will impact the results as you may miss a valuable POI or a valuable pointer. I don't see any other possibility than multi-threading (which by the way is already implemented) to speed up the search.

**Comment by nikaiw** [comment]
Yeah, I tried reducing the size of the binary too and was disappointed by the inaccurate results. I just felt like it could be the decision of the user to reduce the POI with a
the accepted increased risk of no valuable results. But I totally understand this might not be appealing to perform this change to avoid users being misguided (likely to use this and be disappointed by the results).
